site_name: Static HTML Builder

theme: readthedocs

pages:
  - [index.md, Home]
  - [getting-started.md, 开始使用]
  - [tutorial.md, 教程]
  - [advenced.md, 高级技巧]
  - [deploy.md,应用部署]
  - [recommend.md, 推荐模块]
  - [cordova.md, 手机应用打包帮助]
  - [release.md, 版本历史]

repo_url: https://github.com/ETENG-WIKI/static-html-builder

google_analytics: ['UA-62410339-1', 'auto']
